'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {categories,useShop} from './ShopProvider';
import {CountrySelector,Modal} from './UI';
import Icon from './Icon';
export function Logo(){return <Link className="logo" href="/">NOVA<small className="wear-mark">WEAR</small></Link>}
export default function StoreShell({children}){const s=useShop(),router=useRouter();const [search,setSearch]=useState(false),[menu,setMenu]=useState(false);return <><div className="announcement">Prendas para todos tus días. <span>Envío gratis desde {s.money(s.market.freeShipping)}</span></div><div className="wrap"><header className="nav"><Logo/><nav className="navlinks"><Link href="/productos">Comprar todo</Link>{categories.slice(0,4).map(c=><Link key={c} href={`/productos?categoria=${encodeURIComponent(c)}`}>{c}</Link>)}<Link href="/ofertas">Ofertas</Link></nav><div className="navright"><button className="iconbutton mobilemenu" onClick={()=>setMenu(true)} aria-label="Abrir menú"><Icon name="menu"/></button><button className="iconbutton" onClick={()=>setSearch(!search)} aria-label="Buscar"><Icon name="search"/></button><Link className="iconbutton" href="/favoritos" aria-label="Favoritos"><Icon name="heart"/></Link><Link className="iconbutton" href="/carrito" aria-label="Carrito"><Icon name="bag"/><span className="count">{s.cart.reduce((n,i)=>n+i.qty,0)}</span></Link><Link className="adminlink" href="/admin">Admin ↗</Link></div></header><div className="marketbar"><span>Comprando en <strong>{s.market.name}</strong> <span className="marketdescription">· Selección y precios de tu tienda</span></span><CountrySelector/></div>{search&&<form className="searchbar" onSubmit={e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q');router.push('/productos?q='+encodeURIComponent(q));setSearch(false)}}><input name="q" placeholder="¿Qué estás buscando?" aria-label="Buscar producto" autoFocus/><button className="btn small">Buscar</button></form>}</div>{children}<Footer/>{menu&&<Modal title="Explora NOVA WEAR" onClose={()=>setMenu(false)}><Link className="menu-link" href="/productos" onClick={()=>setMenu(false)}>Comprar todo</Link>{categories.map(c=><Link className="menu-link" key={c} href={`/productos?categoria=${encodeURIComponent(c)}`} onClick={()=>setMenu(false)}>{c}</Link>)}<Link className="menu-link" href="/admin" onClick={()=>setMenu(false)}>Administración ↗</Link></Modal>}</>}
function Footer(){const s=useShop();return <><div className="wrap"><section className="newsletter"><div><h3>Las buenas cosas llegan primero aquí.</h3><p>Nuevas colecciones y prendas que vale la pena descubrir.</p></div><form onSubmit={e=>{e.preventDefault();s.toast('Suscripción simulada. No se ha enviado tu correo.');e.currentTarget.reset()}}><input type="email" required placeholder="Tu correo electrónico" aria-label="Correo electrónico"/><button aria-label="Suscribirse"><Icon name="arrow"/></button></form></section></div><footer className="footer"><div className="wrap"><div className="footergrid"><div><Logo/><p>Prendas que se sienten como tú.<br/>Para vestirte a tu manera, cada día.</p></div><div><h4>Explora</h4><Link href="/productos">Todas las prendas</Link><Link href="/productos?categoria=Camisas">Camisas</Link><Link href="/productos?categoria=Pantalones">Pantalones</Link></div><div><h4>Tu compra</h4><Link href="/carrito">Carrito</Link><Link href="/informacion/envios">Envíos y devoluciones</Link><Link href="/informacion/ayuda">Ayuda</Link></div><div><h4>NOVA Studio</h4><Link href="/admin">Administración</Link><Link href="/informacion/nosotros">Sobre NOVA</Link><Link href="/informacion/imagenes">Créditos de imágenes</Link></div></div><div className="footerbottom"><span>© 2026 NOVA WEAR · Compras simuladas.</span><span>{s.market.flag} {s.market.name} · {s.market.currency}</span></div></div></footer></>}
