'use client';
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import Icon from './Icon';
import {useShop} from './ShopProvider';
export function Photo({name,alt='',priority=false,...props}){return <Image src={`/assets/${name}.jpg`} alt={alt} width={1200} height={1500} priority={priority} {...props}/>}
export function Modal({title,children,onClose}){const ref=useRef(null);useEffect(()=>{const d=ref.current;d.showModal();return()=>d.close()},[]);return <dialog ref={ref} onClose={onClose}><button className="iconbutton close" onClick={onClose} aria-label="Cerrar"><Icon name="close"/></button><h2>{title}</h2>{children}</dialog>}
export function CountrySelector(){const [open,setOpen]=useState(false);const s=useShop();return <><button className="countrybutton" onClick={()=>setOpen(true)} aria-label="Cambiar país"><span>{s.market.flag}</span><strong>{s.market.name}</strong><span className="currencycode">{s.market.currency}</span><span>⌄</span></button>{open&&<Modal title="Elige dónde comprar." onClose={()=>setOpen(false)}><p className="countryintro">Cada tienda tiene su propia selección, precios e inventario. Conservamos tu carrito por país durante esta sesión.</p><div className="countryoptions">{Object.entries(s.markets).map(([code,m])=><button key={code} className={`countryoption ${code===s.country?'selected':''}`} aria-pressed={code===s.country} onClick={()=>{s.changeCountry(code);setOpen(false)}}><span className="countryflag">{m.flag}</span><span><strong>{m.name}</strong><small>{m.currencyName} · {m.currency}<br/>{s.stores[code].products.length} productos disponibles</small></span><span className="countrytick"><Icon name={code===s.country?'check':'chevron'}/></span></button>)}</div><p className="countryfoot">Precios de demostración definidos por tienda.</p></Modal>}</>}
export function ProductCard({product:p}){const s=useShop();return <article className="product"><div className="productimage"><Link href={`/producto/${p.id}`} aria-label={`Ver ${p.name}`}><Photo name={p.image} alt={p.name}/></Link><span className={`tag ${p.old?'sale':''}`}>{p.stock>0?p.tag:'AGOTADO'}</span><button className={`iconbutton heart ${s.favorites.includes(p.id)?'selected':''}`} aria-label={`Guardar ${p.name}`} aria-pressed={s.favorites.includes(p.id)} onClick={()=>s.favorite(p.id)}><Icon name="heart"/></button><Link className="quickadd" href={`/producto/${p.id}`}>Elegir talla</Link></div><div className="productmeta"><div><Link href={`/producto/${p.id}`}><h3>{p.name}</h3></Link><div className="productcat">{p.cat} · {p.gender}</div></div><div className="price">{s.money(p.price)}{p.old>p.price&&<span className="oldprice">{s.money(p.old)}</span>}</div></div><div className="swatches">{p.colors.map(c=><i key={c} style={{background:c}}/>)}</div></article>}
export function Status({value}){return <span className={`status ${['Entregado','Activo'].includes(value)?'green':value==='En camino'?'blue':'amber'}`}>{value}</span>}
export function Empty({title,children}){return <div className="empty"><Icon name="search"/><h2>{title}</h2>{children}</div>}
